### PR TITLE
suggested favicon logo added

### PR DESCRIPTION
**Pull request by pranjalee30**
suggested improvement made

### CODE REVIEW

**Comment by anisharaz** [comment]
@pranjalee30 perfect , can you please send me the link to the logo files.

**Comment by pranjalee30** [comment]
@anisharaz, [favicon_ico](https://drive.google.com/drive/folders/1c37pmEg3HTNeWQB93HwX-N-RZjNl67mE?usp=sharing)

This is my drive link you can take the logo files from here.
Kindly Merge it and give review.

Thank You

**Comment by anisharaz** [comment]
@pranjalee30 Thankyou For the contribution

**Comment by anisharaz** [comment]
@pranjalee30 can you please open a new pull request , something was broken and i had to revert.

**Pull request merged**
