### PR TITLE
frontend UI

### PR DESCRIPTION
**Pull request by biplab-sutradhar**

### CODE REVIEW

**Comment by anisharaz** [comment]
@biplab-sutradhar Please add a screenshot

**Comment by biplab-sutradhar** [comment]
image

**Comment by biplab-sutradhar** [comment]
image

**Comment by anisharaz** [comment]
@biplab-sutradhar its a good start , but its far form the figma design , if you promiss to make exactly like given figma design then i can assign the frontend UI issue to you.

**Comment by biplab-sutradhar** [comment]
there are few alignment mistakes but the thing is this repo is not active at all so I can't give much time in it

**Comment by anisharaz** [comment]
are you going to complete this UI as in figma ?. I not i am bound to close the pull request.

**Pull request closed without merging**
